version: '3.7' 

services:
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 7379:6379
      
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - 37017:27017
      
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: miniShop
      MYSQL_USER: minishop
      MYSQL_PASSWORD: password